### ISSUE TITLE
Externals XML tool files when running C/C++ analysis

### ISSUE THREAD

**Issue by AnatoleAnacrouse** [lequal/docker-cat#15]
The first step when running C/C++ analysis is to launch externals Tools (cppcheck, Rats, etc.).

Each of these tools generates an XML result file located in the workspace directory.

So that if the source directory is the same as the workspace, the XML files will be scanned in the next step.

**Comment by Sancretor** [comment]
SonarQube analysis depends on what's inside the `sonar-project.properties` file.
Have you tried to add the `sonar.exclusions` property to exclude those files from the analysis' scope ?

Something like this for example : 
`sonar.exclusion=cppcheck-report.xml,rats-report.xml,vera-report.xml`

**Comment by Sancretor** [comment]
No answer in nearly two months, we consider the issue as outdated.
