### ISSUE TITLE
Build of master branch is broken

### ISSUE THREAD

**Issue by begarco** [lequal/docker-cat#19]
## Issue
Master branch does not build anymore.

See https://cloud.docker.com/u/lequal/repository/registry-1.docker.io/lequal/docker-cat/builds/12b749bc-fd22-428b-bee0-646becae95e2

## Solution
Update links to broken dependencies.

**Comment by Sancretor** [comment]
Fixed in "dev" branch by #13 merged Pull Request

**Comment by Sancretor** [comment]
Merged into master, for 1.0.3 release
