### ISSUE TITLE
java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by Xispa33** [lequal/docker-cat#22]
Hi,
First of all, thank you for sharing us this repo.
I have been trying to use docker-cat on a CentOS 7 VM, unfortunately I'm stuck...
Here is the command I executed:

`docker run -v /Docker:/media/sf_Shared:rw -p 9000:9000 -p 9001:9001 -e ALLOWED_GROUPS="1000" lequal/docker-cat
`
The error says _"web[][o.s.s.p.Platform] Web server startup failed"_ and was caused by _"java.util.zip.ZipException: error in opening zip file"_

Here the logs obtained after running the command
`[INFO] Docker-cat is now adding user permissions to Sonarqube.
[INFO] Docker-cat is giving group permissions GID no. 1000 to Sonarqube.
[INFO] Docker-cat permissions for sonarqube finished.
[INFO] docker-cat, initiating connection with Sonarqube.
2019.08.07 15:24:44 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2019.08.07 15:24:44 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2019.08.07 15:24:44 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonarqube/temp/conf/es
2019.08.07 15:24:44 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2019.08.07 15:24:54 INFO  app[][o.e.p.PluginsService] no modules loaded
2019.08.07 15:24:54 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
[INFO] docker-cat, retrieving Sonarqube's service status..
[INFO] docker-cat, detected status for Sonarqube, expecting it to be UP..
[INFO] docker-cat, retrieving Sonarqube's service status..
[INFO] docker-cat, detected status for Sonarqube, expecting it to be UP..
2019.08.07 15:25:19 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2019.08.07 15:25:19 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonarqube]: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -cp ./lib/common/*:./lib/server/*:/opt/sonarqube/lib/jdbc/h2/h2-1.3.176.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process1789222769243259198properties
2019.08.07 15:25:22 INFO  web[][o.s.p.ProcessEntryPoint] Starting web
2019.08.07 15:25:24 INFO  web[][o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
[INFO] docker-cat, retrieving Sonarqube's service status..
2019.08.07 15:25:27 INFO  web[][o.e.p.PluginsService] no modules loaded
2019.08.07 15:25:27 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
2019.08.07 15:25:27 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
2019.08.07 15:25:27 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
2019.08.07 15:25:27 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2019.08.07 15:25:31 INFO  web[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [127.0.0.1:9001]
2019.08.07 15:25:31 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 6.7.4.38452 / b62b59da1adf991c41ed0730684f813d4116f6cc
2019.08.07 15:25:32 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Starting embedded database on port 9092 with url jdbc:h2:tcp://127.0.0.1:9092/sonar
2019.08.07 15:25:32 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Embedded database started. Data stored in: /opt/sonarqube/data
2019.08.07 15:25:32 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:h2:tcp://127.0.0.1:9092/sonar
2019.08.07 15:25:32 WARN  web[][o.s.d.DatabaseChecker] H2 database should be used for evaluation purpose only
2019.08.07 15:25:34 INFO  web[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /opt/sonarqube
2019.08.07 15:25:34 INFO  web[][o.s.s.u.SystemPasscodeImpl] System authentication by passcode is disabled
2019.08.07 15:25:34 INFO  web[][o.s.s.p.d.m.h.MigrationHistoryTableImpl] Creating table schema_migrations
2019.08.07 15:25:34 ERROR web[][o.s.s.p.Platform] Web server startup failed
java.lang.IllegalStateException: Unable to read plugin manifest from jar : /opt/sonarqube/extensions/plugins/sonar-cnes-scan-plugin-1.3.jar
	at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:125)
	at org.sonar.core.platform.PluginInfo.create(PluginInfo.java:395)
	at org.sonar.server.plugins.ServerPluginRepository.loadPreInstalledPlugins(ServerPluginRepository.java:142)
	at org.sonar.server.plugins.ServerPluginRepository.start(ServerPluginRepository.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:134)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevel2.start(PlatformLevel2.java:92)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel2Container(Platform.java:177)
	at org.sonar.server.platform.Platform.init(Platform.java:87)
	at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:45)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:120)
	... 32 common frames omitted
2019.08.07 15:25:36 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Embedded database stopped
[INFO] docker-cat, detected status for Sonarqube, expecting it to be UP..
2019.08.07 15:25:37 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2019.08.07 15:25:38 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2019.08.07 15:25:38 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
2019.08.07 15:25:38 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
`
I'm really new to docker, I spent half a day trying to solve this issue unsuccessfully. Maybe there is something wrong with the parameters I entered, even though I am sure of the group ID.
Any help would really be appreciated.

I remain at your disposal if you need any additional information.

Cheers,

**Comment by louisjdmartin** [comment]
Hello,
Thanks for reporting the issue.
I'm going to investigate but the issue may be caused by anoter issue in the sonar-cnes-scan plugin (see https://github.com/lequal/sonar-cnes-scan-plugin/issues/10 ). It's possible that the docker image use the old plugin. I'm going to update the docker image as soon as possible.

For now, you can rebuild the docker on your machine, for that you can use the following script:

```
git clone https://github.com/lequal/docker-cat.git
cd docker-cat
docker build -t docker-cat .
docker run -v /Docker:/media/sf_Shared:rw -p 9000:9000 -p 9001:9001 -e ALLOWED_GROUPS="1000" docker-cat
```

**Comment by louisjdmartin** [comment]
Issue solved and image updated.

Your command should work, pull the latest build then retry to execute docker-CAT.
```
docker pull lequal/docker-cat
docker run -v /Docker:/media/sf_Shared:rw -p 9000:9000 -p 9001:9001 -e ALLOWED_GROUPS="1000" lequal/docker-cat
```

If there is another problem feel free to report it on this thread by re-opening the issue.
Cheers

**Comment by Xispa33** [comment]
Hi,

Thanks for the previous help ! It actually solved the error ! 

However, I still have one question: after you made the changes, when I executed docker-CAT the terminal gets stuck (the file attached corresponds to the logs received).  
[sonar.txt](https://github.com/lequal/docker-cat/files/3492129/sonar.txt)
Opening another Terminal, when I run command  :
`docker image ls` 
I get the output:
```
REPOSITORY           TAG                IMAGE ID               CREATED            SIZE
lequal/docker-cat   latest              0838fa39a206        4 days ago          1.98GB
sonarqube              6.7.4            9834bf466fe4        13 months ago       821MB

```
And when I run:
`docker container ls`
 I get :
```
CONTAINER ID       IMAGE                    COMMAND          CREATED             STATUS              PORTS   
1483026693fe        lequal/docker-cat   "/tmp/init.bash"    2 days ago          Up 2 days           0.0.0.0:9000-9001->9000-9001/tcp   serene_ramanujan
```
So, considering this, I believe the docker-cat and sonarqube container are up and running, do you confirm ? Or, seeing the logs, is it working correctly ? 


My goal using docker-cat is to build code written in C. The code is located in a specific folder and the tools needed to compile and build (GCC for instance) are in the same repo. How do I use docker-cat to run an analysis on my repo ? Or more simply, how do I integrate it in the docker ?



Thank you very much for your time. 

Cheers,

**Comment by louisjdmartin** [comment]
Hi,

You can hide logs and run docker in the background by adding the `-d` arguments in docker run:

```
docker run -d -v /Docker:/media/sf_Shared:rw -p 9000:9000 -p 9001:9001 -e ALLOWED_GROUPS="1000" lequal/docker-cat
```

In your case, if you stop docker-cat by using `CTRL+C` you can restart it with `docker start serene_ramanujan`

Use `docker ps -a` to see all active runner and `docker rm <NAME>` to do some cleaning if needed ;)



With what you said, docker-cat looks to run. To run analysis on your repo, clone it in the folder shared with docker (`/Docker`) then open http://localhost:9000 => Login => admin/admin => More => CNES Analisys.

You can visit this documentation for more information if needed: https://lequal.github.io/CAT/how-to-use-cat#using-docker-cat

PS: This documentation is very recent, we are open to any suggestion to improve it.

Cheers

**Comment by Xispa33** [comment]
Hi,
Thanks for your reply which allowed me to go further again! However, I am coming back to you because I still have a problem..

So I did as you adviced me to do: cloned the repo in /Docker, opened  http://localhost:9000, logged in and then ran a CNES Analysis (and read the doc sent, which corresponded to your instructions).

Here are the logs I received 
[sonarlogs.txt](https://github.com/lequal/docker-cat/files/3497171/sonarlogs.txt)

Seeing the logs, do you have any idea why the execution failed ? Is the problem due to an error in the docker image maybe? I am not sure of the parameter "Source" I entered either. 

Also, to run an analysis, I had to add 3 files at the root of my repo: _scan-project.properties_, _cat-scan-script.sh_ and _.cat-sonar-scanner.log_. Maybe adding this to the doc would be useful in my opinion. Apart from that I think the doc is very clear :)
 
Thanks again very much for your time.

Cheers,

**Comment by louisjdmartin** [comment]
Hi

In your logs i see an AccessDeniedException. Maybe there is some problems with the shared folder, check if sonar can acces to the folder with read/write permissions.

For the "source" parameter, if C files are located in `/Docker/HelloWorldC/`, the parameter is correct. If C files are located in folder like  `/Docker/HelloWorldC/src` you should set this parameter to `src`


Cheers

**Comment by Xispa33** [comment]
Hi,
Changing the permissions solved the problem, sonarqube is working properly now, so thank you very much !
I just have one last question: I want to change this image by adding new tools. So I have been trying to re-builb the image by cloning this repo and then build it:
```
docker build -t docker-cat .
``` 
Unfortunately the building seems to fail at step 14 as you can see on the log file.
[logsbuild.txt](https://github.com/lequal/docker-cat/files/3501858/logsbuild.txt)

Is the issue due to the repo itself ?
Cheers,

**Comment by louisjdmartin** [comment]
Hi
According to your logs, the error come from your network.

Please check that your machine can access to http://deb.debian.org/debian/dists/stretch-updates/InRelease.

The build need to be connected to debian repo to download some tools.

Cheers
