### ISSUE TITLE
Complete community information for docker-cat

### ISSUE THREAD

**Issue by begarco** [lequal/docker-cat#33]
### Expected behavior
The project should provide more information for the community:
- Template for issues and merge requests
- License
- Governance
- Detailed README (usage, install, build, version matrix)

### Actual behavior
There is only few information in the readme.

### Steps to reproduce behavior
See GitHub repo.

### Detection version
All until 2.0.1

**Comment by sdinot** [comment]
At the very least, a license would be welcome to know the conditions of a potential contribution.
