### ISSUE TITLE
Docker-car uses H2 database 

### ISSUE THREAD

**Issue by AnatoleAnacrouse** [lequal/docker-cat#4]
containers use a H2 database that does not handle large volume of data.

At the bottoms of the dashboard pages, the following message appears : 

Embedded database should be used for evaluation purpose only. The embedded database will not scale, it will not support upgrading to newer versions of SonarQube, and there is no support for migrating your data out of it into a different database engine."

What about using an other DB like Postgres, MysSQL, etc.?

Thanx

**Comment by WaldoFR** [comment]
Hi, 

There is two way to solve this issue : 
* If you already have a remote database, specify during the launch the following parameters (with `docker run`) : 
  *  -e SONARQUBE_JDBC_USERNAME=sonar
  * -e SONARQUBE_JDBC_PASSWORD=sonar
  * -e SONARQUBE_JDBC_URL=jdbc:postgresql://localhost/sonar
* If you don't : 
  * download the [`docker-compose.yml`](https://github.com/lequal/docker-cat/blob/master/docker-compose.yml)
  * Change the `ALLOWED_GROUP` parameter using a text editor. 
  * [Install docker compose](https://docs.docker.com/compose/install/)
  * Run the container with the **PostgreSQL** specified in `docker-compose.yml` using the command `docker-compose up`

Regards.
